

services:
  flask-app:
    build: .
    container_name: flask_app
    ports:
      - "5050:5000"
    env_file:
      - production.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
